//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DyningManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Border
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public string Session { get; set; }
        public int Room { get; set; }
        public byte[] Image { get; set; }
        public string BorderId { get; set; }
    }
}
