//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DyningManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Floor
    {
        public int FloorId { get; set; }
        public string Floor1 { get; set; }
    }
}
