//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DyningManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal
    {
        public int MealId { get; set; }
        public Nullable<double> Meal1 { get; set; }
        public string Date { get; set; }
        public Nullable<int> Payment { get; set; }
        public string BorderId { get; set; }
    }
}
